### ISSUE TITLE
Error when creating payment 

### ISSUE THREAD

**Issue by AlaaL** [frappe/webshop#204]
I am not able to procced after pressing the pay button on sales order from web portal i get the following error

`Error Log st6otsfmnm: 'Title' (Traceback (most recent call last): 
File "apps/payments/payments/payment_gateways/doctype/stripe_settings/stripe_settings.py", line 251, in finalize_request ).run_method("on_payment_authorized", self.flags.status_changed_to) File "apps/frappe/frappe/model/document.py", line 962, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "apps/frappe/frappe/model/document.py", line 1322, in composer return composed(self, method, *args, **kwargs) File "apps/frappe/frappe/model/document.py", line 1304, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "apps/frappe/frappe/model/document.py", line 959, in fn return method_object(*args, **kwargs) File "apps/webshop/webshop/webshop/doctype/override_doctype/payment_request.py", line 43, in on_payment_authorized self.set_as_paid() File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 281, in set_as_paid self.make_invoice() File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 217, in make_invoice si = si.insert(ignore_permissions=True) File "apps/frappe/frappe/model/document.py", line 292, in insert self._validate() File "apps/frappe/frappe/model/document.py", line 574, in _validate self._validate_mandatory() File "apps/frappe/frappe/model/document.py", line 911, in _validate_mandatory raise frappe.MandatoryError( frappe.exceptions.MandatoryError: [Sales Invoice, BTB2024000000001]: taxes ) will get truncated, as max characters allowed is 140

Error Log st6o982crp: 'Title' (Traceback (most recent call last): File "apps/payments/payments/payment_gateways/doctype/stripe_settings/stripe_settings.py", line 251, in finalize_request ).run_method("on_payment_authorized", self.flags.status_changed_to) File "apps/frappe/frappe/model/document.py", line 962, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "apps/frappe/frappe/model/document.py", line 1322, in composer return composed(self, method, *args, **kwargs) File "apps/frappe/frappe/model/document.py", line 1304, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "apps/frappe/frappe/model/document.py", line 959, in fn return method_object(*args, **kwargs) File "apps/webshop/webshop/webshop/doctype/override_doctype/payment_request.py", line 43, in on_payment_authorized self.set_as_paid() File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 281, in set_as_paid self.make_invoice() File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 217, in make_invoice si = si.insert(ignore_permissions=True) File "apps/frappe/frappe/model/document.py", line 292, in insert self._validate() File "apps/frappe/frappe/model/document.py", line 574, in _validate self._validate_mandatory() File "apps/frappe/frappe/model/document.py", line 911, in _validate_mandatory raise frappe.MandatoryError( frappe.exceptions.MandatoryError: [Sales Invoice, BTB2024000000001]: taxes During handling of the above exception, another exception occurred: Traceback (most recent call last): File "apps/payments/payments/payment_gateways/doctype/stripe_settings/stripe_settings.py", line 202, in create_request return self.create_charge_on_stripe() File "apps/payments/payments/payment_gateways/doctype/stripe_settings/stripe_settings.py", line 238, in create_charge_on_stripe return self.finalize_request() File "apps/payments/payments/payment_gateways/doctype/stripe_settings/stripe_settings.py", line 253, in finalize_request frappe.log_error(frappe.get_traceback()) File "apps/frappe/frappe/utils/error.py", line 76, in log_error return error_log.insert(ignore_permissions=True) File "apps/frappe/frappe/model/document.py", line 292, in insert self._validate() File "apps/frappe/frappe/model/document.py", line 578, in _validate self._validate_length() File "apps/frappe/frappe/model/base_document.py", line 972, in _validate_length self.throw_length_exceeded_error(df, max_length, value) File "apps/frappe/frappe/model/base_document.py", line 1009, in throw_length_exceeded_error frappe.throw( File "apps/frappe/frappe/__init__.py", line 645, in throw msgprint( File "apps/frappe/frappe/__init__.py", line 610, in msgprint _raise_exception() File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception raise exc frappe.exceptions.CharacterLengthExceededError: 

Error Log st6otsfmnm: 'Title' (Traceback (most recent call last): File "apps/payments/payments/payment_gateways/doctype/stripe_settings/stripe_settings.py", line 251, in finalize_request ).run_method("on_payment_authorized", self.flags.status_changed_to) File "apps/frappe/frappe/model/document.py", line 962, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "apps/frappe/frappe/model/document.py", line 1322, in composer return composed(self, method, *args, **kwargs) File "apps/frappe/frappe/model/document.py", line 1304, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "apps/frappe/frappe/model/document.py", line 959, in fn return method_object(*args, **kwargs) File "apps/webshop/webshop/webshop/doctype/override_doctype/payment_request.py", line 43, in on_payment_authorized self.set_as_paid() File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 281, in set_as_paid self.make_invoice() File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 217, in make_invoice si = si.insert(ignore_permissions=True) File "apps/frappe/frappe/model/document.py", line 292, in insert self._validate() File "apps/frappe/frappe/model/document.py", line 574, in _validate self._validate_mandatory() File "apps/frappe/frappe/model/document.py", line 911, in _validate_mandatory raise frappe.MandatoryError( frappe.exceptions.MandatoryError: [Sales Invoice, BTB2024000000001]: taxes ) will get truncated, as max characters allowed is 140 ) will get truncated, as max characters allowed is 140`

**Comment by petkovdavid** [comment]
I just had the same issue and its due for Customer not having read permissions on doctypes `Account` & `Payment Entry`. Quick fix is overriding PaymentRequest.on_payment_authorized method so it changes the user to Admin then returning it to the previous user.
I am not sure of the security issues it can cause.
