### ISSUE TITLE
ModuleNotFoundError: No module named 'webshop'

### ISSUE THREAD

**Issue by kevinbrown1980** [frappe/webshop#34]
After installing the app I can no longer access the website or desk, i get the below error

ModuleNotFoundError

ModuleNotFoundError: No module named 'webshop'
Traceback (most recent call last)

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response

    endpoint, renderer_instance = path_resolver.resolve()

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve

    resolve_redirect(self.path, request.query_string)

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 108, in resolve_redirect

    redirects += frappe.get_all("Website Route Redirect", ["source", "target"], order_by=None)

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1974, in get_all

    return get_list(doctype, *args, **kwargs)

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1949, in get_list

    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/db_query.py", line 179, in execute

    if is_virtual_doctype(self.doctype):

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/caching.py", line 123, in site_cache_wrapper

    return func(*args, **kwargs)

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/utils/__init__.py", line 133, in is_virtual_doctype

    if frappe.db.has_column("DocType", "is_virtual"):

    File "/home/ubuntu/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__

    obj = instance._get_current_object()

    File "/home/ubuntu/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 490, in _get_current_object

    raise RuntimeError(unbound_message) from None

    During handling of the above exception, another exception occurred:
    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/middlewares.py", line 16, in __call__

    return super().__call__(environ, start_response)

    File "/home/ubuntu/frappe-bench/env/lib/python3.10/site-packages/werkzeug/middleware/shared_data.py", line 249, in __call__

    return self.app(environ, start_response)

    File "/home/ubuntu/frappe-bench/env/lib/python3.10/site-packages/werkzeug/middleware/shared_data.py", line 249, in __call__

    return self.app(environ, start_response)

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 74, in application

    app(environ, start_response),

    File "/home/ubuntu/frappe-bench/env/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 189, in application

    resp = f(*args[:-2] + (request,))

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 128, in application

    response = handle_exception(e)

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 389, in handle_exception

    response = get_response("message", http_status_code=http_status_code)

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response

    response = ErrorPage(exception=e).render()

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__

    super().__init__(path=path, http_status_code=http_status_code)

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__

    self.set_template_path()

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path

    app_path = frappe.get_app_path(app)

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1438, in get_app_path

    return get_pymodule_path(app_name, *joins)

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1468, in get_pymodule_path

    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))

    File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1409, in get_module

    return importlib.import_module(modulename)

    File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked

    ModuleNotFoundError: No module named 'webshop'

**Comment by tomemmerson** [comment]
+1, Also getting this - tried uninstalling/installing multiple times. Building from the official docker image (v15)

**Comment by Nicolas-Che** [comment]
+1， anyone have solution?

**Comment by Xinftrju** [comment]
Please try “bench --site default uninstall-app webshop”, and then reinstall “bench --site default install-app webshop”

**Comment by NagariaHussain** [comment]
Unrelated to webshop. Closing.
