### ISSUE TITLE
ModuleNotFoundError: No module named 'webshop.patches.after_install'

### ISSUE THREAD

**Issue by sharad740** [frappe/webshop#38]
┌──(jarvis㉿kali)-[/frappe_new/frappe-15]
└─$ bench install-app webshop
App payments already installed
App erpnext already installed

Installing webshop...
An error occurred while installing webshop: No module named 'webshop.patches.after_install'
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 306, in install_app
    frappe.get_attr(after_install)()
  File "apps/webshop/webshop/setup/install.py", line 9, in after_install
    run_patches()
  File "apps/webshop/webshop/setup/install.py", line 236, in run_patches
    frappe.get_attr(f"webshop.patches.after_install.{patch}.execute")()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1679, in get_attr
    return getattr(get_module(modulename), methodname)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1415, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'webshop.patches.after_install'

**Comment by Nicolas-Che** [comment]
+1, I have the same issue. Do you have any solution?

**Comment by legolas108** [comment]
Had the same problem. Tried `bench --site <sitename> install-app --force webshop` and it finished without error. Not sure though it's all good under the hood. Need to test now.

**Comment by NagariaHussain** [comment]
This seems to be fixed in a later commit.
