### ISSUE TITLE
Error while placing an order on Webshop

### ISSUE THREAD

**Issue by simran-baliyan** [frappe/webshop#86]
When we try to place an order on Webshop, it throws an error.
Kindly fix it.

![Screenshot 2024-02-03 221104](https://github.com/frappe/webshop/assets/158838687/6151092f-831f-4dec-aae3-3cb617701d3f)

**Comment by simran-baliyan** [comment]
Traceback (most recent call last):
  File "apps/frappe/frappe/[app.py](https://app.py/)", line 106, in application
    frappe.handler.handle()
  File "apps/frappe/frappe/[handler.py](https://handler.py/)", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/[handler.py](https://handler.py/)", line 85, in execute_cmd
    return [frappe.call](https://frappe.call/)(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1684, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_[validations.py](https://validations.py/)", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/webshop/webshop/webshop/shopping_cart/[cart.py](https://cart.py/)", line 135, in place_order
    sales_order.insert()
  File "apps/frappe/frappe/model/[document.py](https://document.py/)", line 286, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/[document.py](https://document.py/)", line 1085, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/[document.py](https://document.py/)", line 954, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/[document.py](https://document.py/)", line 1320, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/[document.py](https://document.py/)", line 1304, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/[transaction.py](https://transaction.py/)", line 1309, in validate_transaction
    valid_accounts = validate_gst_accounts(doc, is_sales_transaction) or ()
  File "apps/india_compliance/india_compliance/gst_india/overrides/[transaction.py](https://transaction.py/)", line 344, in validate_gst_accounts
    _throw(
  File "apps/india_compliance/india_compliance/gst_india/overrides/[transaction.py](https://transaction.py/)", line 228, in _throw
    frappe.throw(message, title=title or _("Invalid GST Account"))
  File "apps/frappe/frappe/__init__.py", line 578, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 550, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 501, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Row #1: Cannot charge IGST for intra-state supplies
