### ISSUE TITLE
Information about bug

### ISSUE THREAD

**Issue by soome-Rs** [frappe/webshop#95]
Hi Guys, i've got Error while Rename item Code

![2024-02-16_09-50](https://github.com/frappe/frappe/assets/4391256/579630a6-85ed-4ad5-bda4-729c56690db7)

![Screenshot 2024-02-16 095250](https://github.com/frappe/frappe/assets/4391256/61eb4418-3bf3-4cbe-9f82-882cf69d4889)

**App Versions**

`
crm 0.0.1
erpnext 15.14.0
frappe 15.14.0
hrms 15.11.1
ksa 0.0.1
payments 0.0.1
webshop 0.0.1
`

**Traceback**

`
Traceback (most recent call last):
  File "apps/frappe/frappe/model/document.py", line 1614, in execute_action
    getattr(doc, __action)(**kwargs)
  File "apps/frappe/frappe/model/document.py", line 1020, in _rename
    self.name = rename_doc(doc=self, new=name, merge=merge, force=force, validate=validate_rename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/rename_doc.py", line 206, in rename_doc
    new_doc.run_method("after_rename", old, new, merge)
  File "apps/frappe/frappe/model/document.py", line 940, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1300, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1284, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: execute() takes from 1 to 2 positional arguments but 5 were given
`

**Comment by Govind-Jangid** [comment]
Facing same error
